### ISSUE TITLE
 can't run with 7.13.2

### ISSUE THREAD

**Issue by starinskycc** [fbaligand/kibana-enhanced-table#273]
TypeError: Object(...) is not a function
    at handleCourierRequest (http://kibana.cc/40943/bundles/plugin/enhancedTable/1.13.0/enhancedTable.plugin.js:1754:108)
    at async enhancedTableRequestHandler (http://kibana.cc/40943/bundles/plugin/enhancedTable/1.13.0/enhancedTable.plugin.js:1487:20)
    at async fn (http://kibana.cc/40943/bundles/plugin/enhancedTable/1.13.0/enhancedTable.plugin.js:1943:13)
    at async Execution.invokeFunction (http://kibana.cc/40943/bundles/plugin/expressions/kibana/expressions.plugin.js:1:53783)
    at async Execution.invokeChain (http://kibana.cc/40943/bundles/plugin/expressions/kibana/expressions.plugin.js:1:52867)

**Comment by fbaligand** [comment]
Hi,

Well, some other people managed to make the plugin work with Kibana 7.13.2 (#269), by fully reinstalling the plugin.
You can give it a try.

Question: do you have installed this package?
https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.0/enhanced-table-1.13.0_7.13.2.zip

**Comment by fbaligand** [comment]
Given that the issue is not reproducible, and there is no feedback since several months, I close the issue.
