### ISSUE TITLE
Not working with 7.13.2

### ISSUE THREAD

**Issue by ruria** [fbaligand/kibana-enhanced-table#269]
Hi,
1. I´ve installed Elastic 7.13.2, Kibana 7.13.2 and enhanced table and [enhanced-table-1.13.0_7.13.2.zip](https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.13.0/enhanced-table-1.13.0_7.13.2.zip) on it, from the scratch
2. Load some sample data
3. When creating a new viz (table based or aggregation based) got an error:
 
```

@http://localhost:5601/40943/bundles/plugin/enhancedTable/1.13.0/enhancedTable.plugin.js:1754:108
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]

```

**Comment by fbaligand** [comment]
Surprising.
Could you fully remove your browser cache (using Ctrl+Shift+Suppr) and then fully reload page (using Shift+F5) and check if you reproduce the error?

**Comment by ruria** [comment]
I´ve tried removing cache, in developer console with "Disable cahce" (that´s for Chromium and Chrome), and manually removing local and session storage. I´ve tried with Safari an Firefox too ;-(

All this browser cames to the same erorr, with a little diffrent verbose messages, but at the end all say the same:

`TypeError: Object(...) is not a function
    at handleCourierRequest (http://localhost:5601/40943/bundles/plugin/enhancedTable/1.13.0/enhancedTable.plugin.js:1754:108)
    at async enhancedTableRequestHandler (http://localhost:5601/40943/bundles/plugin/enhancedTable/1.13.0/enhancedTable.plugin.js:1487:20)
    at async fn (http://localhost:5601/40943/bundles/plugin/enhancedTable/1.13.0/enhancedTable.plugin.js:1943:13)
    at async Execution.invokeFunction (http://localhost:5601/40943/bundles/plugin/expressions/kibana/expressions.plugin.js:1:53783)
    at async Execution.invokeChain (http://localhost:5601/40943/bundles/plugin/expressions/kibana/expressions.plugin.js:1:52867)`

**Comment by ruria** [comment]
Something wrong on my side... I don´t know what, but I´ve reinstalled from scratch and now works.
Thank you.

**Comment by fbaligand** [comment]
Happy to know that it finally works!
