### ISSUE TITLE
OpenSearch Dashboards port ?

### ISSUE THREAD

**Issue by ccottam** [fbaligand/kibana-enhanced-table#221]
any interest in porting your plugin to opensearch dashboards?

**Comment by fbaligand** [comment]
Any volunteer to port plugin for Opensearch dashboards?
I’m ready to collaborate.

**Comment by adcalsie2** [comment]
Hi @fbaligand,

great job with this plugin!! I've been using it for the last year with kibana and opendistro releases. Now we're migrating to opensearch and I'm also interested in continuing to use your plugin.

I'm already started to adapt the code to opensearch dashboard naming convections following this guide:

https://github.com/opensearch-project/opensearch-plugins/blob/main/UPGRADING.md#opensearch-dashboards-plugins

Also build and deploy the plugin in my opensearch instance. Plugin visualization types are display correctly for selection but seems to be an error creating one of them:

this error is displayed on the visualization frame:
```
Error
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at kl (https://kibanajc:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:109914)
    at h (https://kibanajc:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:54426)
    at g (https://kibanajc:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:55696)
    at https://kibanajc:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:57709
    at $a (https://kibanajc:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:66589)
    at Ms (https://kibanajc:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:106652)
    at gl (https://kibanajc:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:90018)
    at fl (https://kibanajc:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:89943)
    at ol (https://kibanajc:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:87291)
    at https://kibanajc:5601/1/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:434:45733
```
And this one is displayed in a pop-up:
```
TypeError: getSearchSessionId is not a function
at _callee$ (https://kibana.jc:5601/1/bundles/plugin/enhancedTable/enhancedTable.plugin.js:14:1344869)
at tryCatch (https://kibana.jc:5601/1/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:33827)
at Generator.invoke [as _invoke] (https://kibana.jc:5601/1/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:37778)
at Generator.next (https://kibana.jc:5601/1/bundles/plugin/queryWorkbenchDashboards/queryWorkbenchDashboards.plugin.js:1:34966)
at visualization_fn_asyncGeneratorStep (https://kibana.jc:5601/1/bundles/plugin/enhancedTable/enhancedTable.plugin.js:14:1340577)
at _next (https://kibana.jc:5601/1/bundles/plugin/enhancedTable/enhancedTable.plugin.js:14:1340904)
```

Maybe you can create a new repo called something like _opensearch-dashboards-enhanced-table_, I can share with you code customizations.

Thanks for your help.

**Comment by fbaligand** [comment]
Hi,

As you asked, I just created a branch for Dashboards:
https://github.com/fbaligand/kibana-enhanced-table/tree/opensearch-dashboards

To my known, Dashboards is a fork of Kibana 7.10, so the branch I created is a copy of my "7.9" branch that works with Kibana 7.9, 7.10 and 7.11.

That said, concerning your error:
- getSearchSessionId is not used in my branch for Kibana 7.9-7.11 (so opensearch-dashboards branch)
- I guess that you forked master branch, that is for Kibana 7.15
- So I recommend you to fork from "opensearch-dashboards" branch, and restart your migration work

Fabien

**Comment by diego2glez** [comment]
Hi @fbaligand ,

I'm working in the migration using the branch "opensearch-dashboards" you've created. These are the steps I've followed:

1. Replace in order, all files:

	kibana -> opensearchDashboards
	Kibana -> OpenSearchDashboards
	KIBANA -> OPENSEARCH_DASHBOARDS
	kbn -> osd
	Kbn -> Osd
	KBN -> OSD

	opensearchDashboards_legacy -> opensearch_dashboards_legacy
	opensearchDashboards_utils -> opensearch_dashboards_utils
	opensearchDashboards_cloned_code -> opensearch_dashboards_cloned_code
	

2. Rename folder public/src/kibana_cloned_code to public/src/opensearch_dashboards_cloned_code.

3. Rename kibana.json -> opensearch_dashboards.json and change required plugins names:

	{
	  "id": "enhancedTable",
	  "version": "1.11.2",
	  "server": false,
	  "ui": true,
	  "requiredPlugins": [
		"visualizations",
		"data",
		"inspector",
		"opensearchDashboardsLegacy",
		"opensearchDashboardsUtils",
		"opensearchDashboardsReact",
		"share",
		"charts"
	  ]
	}

4. Fix paths and scripts names package.json:

{
  "name": "enhanced-table",
  "version": "1.11.2",
  "description": "This visualization plugin is like a Data Table, but with enhanced features like computed columns, filter bar and pivot table",
  "license": "Apache-2.0",
  "opensearchDashboards": {
    "version": "1.2.0",
    "templateVersion": "1.0.0"
  },
  "scripts": {
    "preinstall": "node ../../preinstall_check",
    "opensearch": "node ../../scripts/opensearch",
    "osd": "node ../../scripts/osd",
    "lint": "../../scripts/eslint .",
    "start": "cd ../.. && node scripts/opensearch_dashboards --dev --oss",
    "debug": "node --nolazy --inspect ../../scripts/opensearch_dashboards --dev",
    "build": "../../plugin-helpers build",
    "compile-and-build": "node ../../scripts/plugin_helpers.js build",
    "compile": "rm -rf ./target && node ../../scripts/build_opensearch_dashboards_platform_plugins.js --scan-dir . --filter enhancedTable"
  },
  "dependencies": {
    "expr-eval": "2.0.2"
  },
  "devDependencies": {
    "dragula": "3.7.2",
    "ui-select": "0.19.8"
  }
}

5. Run "_yarn_" command for dependencies isntallation

6. Compile and build with command "_yarn compile-and-build_"

I build the plugin zip and tested for OpenSearch-Dashboards version 1.0.0 and 1.2.0. After deployment we get this error accesing OpenSearch:

![Screenshot 2022-01-07 132143](https://user-images.githubusercontent.com/26710591/148543456-0093fd2d-ddfa-46a4-a7e5-7263e48cc321.png)

Debugging seems that __ref_ doesn't contains any variable named _expressions_ :(

![image](https://user-images.githubusercontent.com/26710591/148543803-feae4a9e-9234-4d8a-a998-086b97b2ea88.png)

I don't know if this error is going backwards from the _getSearchSessionId_ that appeared when yo try to create/open any visualization type of this plugin or we are progressing.

Maybe you can helps us. I can upload the code if you want.

Diego.

**Comment by fbaligand** [comment]
Well to debug in nice conditions, I invite you to run OpenDashboards in dev mode with enhanced table plugin.
So:
- execute these commands
```
git clone https://github.com/opensearch-project/OpenSearch-Dashboards
cd OpenSearch-Dashboards
git reset --hard X.Y.Z # replace 'X.Y.Z' by desired OpenSearch-Dashboards version
mkdir plugins
cd plugins
git clone https://github.com/fbaligand/kibana-enhanced-table.git enhancedTable
```

- install the version of Node.js listed in the OpenSearch-Dashboards/.node-version file
- ensure that node binary is both in PATH environment variable and in OpenSearch-Dashboards/node folder
- install the latest version of yarn
- execute these commands :
```
cd OpenSearch-Dashboards
yarn opensearch bootstrap
cd plugins/enhancedTable
yarn install
yarn start
```
- in your browser, call http://localhost:5601

**Comment by lambiase** [comment]
Hi @diego2glez ,

would it be possible for you to make the fork with your changes public, such that other people could try it out and help?
Thanks!

**Comment by fbaligand** [comment]
Hi,

For information, @jbgachot wrote a commit that adds Opensearch-Dashboards compatibility.
It should be soon merged on opensearch-dashboards branch.

Here is the discussion about that:
https://github.com/fbaligand/kibana-enhanced-table/discussions/211

**Comment by CCongWang** [comment]
Hi @fbaligand @jbgachot, I'm on opensearch team, thanks for your great effort on porting this plugin to opensearch dashboards! 
Just want to say hi and let you know that we are here to support, feel free to ping me if you see any issues when porting the plugin to opensearch, and I will help with troubleshooting!

**Comment by fbaligand** [comment]
Hi @CCongWang,

Thanks to offer your help!
As you can see, @jbgachot has done a commit that works with open search 1.2. 
it should be become a PR and then be merged on opensearch-dashboard branch. 

So a enhanced-table version for OSD should soon arrive.

**Comment by fbaligand** [comment]
Hi all, 

Great news: enhanced-table is now compatible with OpenSearch Dashboards!

You can get enhanced-table package for OSD in last release (v1.13.1) here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.1

All packages for OSD are suffixed by "_osd-X.Y.Z.zip", where "X.Y.Z" is OSD version.

**Comment by ahopp** [comment]
Super excited to try this out in Dashboards, thanks @fbaligand!

**Comment by fbaligand** [comment]
Happy that you enjoy it! :)

**Comment by giusecagliari** [comment]
hello I am tring to install in osd 1.2 but when I try to install have this error:

```
bin/opensearch-dashboards-plugin install enhancedTable --allow-root
Attempting to transfer from enhancedTable
Attempting to transfer from https://artifacts.opensearch.org/downloads/kibana-plugins/enhancedTable/enhancedTable-1.2.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."
```

**Comment by fbaligand** [comment]
Hi all,

For information, I just published a package for OpenSearch Dashboards 2.0.0.

You can get it here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.1

**Comment by duhang** [comment]
@fbaligand Could you please share how did you build distributable archive for/under OpenSearch Dashboards 2.2.0?

I tried

```
To build a distributable archive, execute this command :

yarn build --kibana-version X.Y.Z # replace 'X.Y.Z' by 2.2.0
```

But I'm getting strange errors like:

```
$ yarn build --kibana-version 2.2.0
yarn run v1.22.17
$ ../../node_modules/.bin/plugin-helpers build --kibana-version 2.2.0
/bin/sh: ../../node_modules/.bin/plugin-helpers: No such file or directory
```

IIUC, one would need opensearch_dashboards.json (which gears towards OSD) instead of kibana.json in order to build under OpenSearch Dashboards 2.2.0. Am I right?

**Comment by fbaligand** [comment]
Hi @duhang,

First, if you just want Enhanced Table "as is" for OpenSearch Dashboards, you don't have to build it, you can simply download the right package here:
https://github.com/fbaligand/kibana-enhanced-table/releases/tag/v1.13.1
The package name is:  enhanced-table-1.13.1_osd-<OSD_VERSION>.zip 

Then, if you want to build it for yourself, I realize that "Development" documentation section was a bit wrong.
So I just did a commit on osd branch to fix that: https://github.com/fbaligand/kibana-enhanced-table/commit/495fa80fc8f8e9b9ff87048c44c7c8561348fc27
Finally, I invite you to pull "osd" branch, and to follow updated "Development" section:
https://github.com/fbaligand/kibana-enhanced-table/tree/osd#development

**Comment by duhang** [comment]
Cool, it totally just worked from "osd" branch:

```
$ node ../../scripts/plugin_helpers.js build --opensearch-dashboards-version 1.2.0
 info deleting the build and target directories
 info running @osd/optimizer
 │ info initialized, 0 bundles cached
 │ info starting worker [1 bundle]
 │ succ 1 bundles compiled successfully after 113 sec
 info copying assets from `public/assets` to build
 info copying server source into the build and converting with babel
 info compressing plugin into [enhancedTable-1.2.0.zip]
✨  Done in 116.50s.
```

A tiny suggestion though:
  One can use --opensearch-dashboards-version flag of "yarn compile-and-build" to specify OSD_VERSION,
  thus avoid from having to manually enter it.

```
yarn compile-and-build --opensearch-dashboards-version <OSD_VERSION>
```

**Comment by fbaligand** [comment]
Indeed, this is a bit easier.
I just updated documentation:
https://github.com/fbaligand/kibana-enhanced-table/tree/osd#development

And happy to see that you appreciate enhanced-table plugin :)

**Comment by hari819** [comment]
i have installed 1.3.2 version of plugin in opensearch dashboards , i can see plugin is installed successfully ,but i am unable to see enhancedTable or its functionality in dashboards, I am trying this in Kubernetes enviroment,

so i will not be able to restart dashboards pod , i tried the troubleshooting steps , but could not get it working  ,please could you help if i am missing some step ,  @fbaligand

**Comment by hari819** [comment]
ignore i could get it working , had to run --optimize command in the Dockerfile after the plugin is installed,

thankyou @fbaligand
